### ISSUE TITLE
Issue when running in GPU

### ISSUE THREAD

**Issue by keyankay** [lbeaucourt/Object-detection#10]
Hi,
Thank you for this code :). However, when i run it on a GPU i get the following error
018-10-04 11:02:34.458511: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.5K (2560 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2018-10-04 11:02:34.465377: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.2K (2304 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Traceback (most recent call last):e: 0 %
File "my-object-detection.py", line 39, in <module>
video(args)
File "/home/ubuntu/object-detection/Object-detection-master/function/video.py", line 99, in video
print("Read frames: %-3i %% -- Write frame: %-3i %%" % (int(countReadFrame/nFrame * 100), int(countWriteFrame/nFrame * 100)), end ='\r')
KeyboardInterrupt
Process ForkPoolWorker-20:

**Comment by lbeaucourt** [comment]
Hello @keyankay ,

Sorry for this late reply ...

In order to use GPU with tensorflow, you shall use another way to install it. For this project I use the CPU tenserflow install process. More information on how to use GPU could be found here:

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

You may have to modify your local Dockerfile to use GPU tensorflow.

Let me know if you need help.

Bye
